"""empty message

Revision ID: 5ee86f15393d
Revises: 
Create Date: 2018-06-05 18:28:12.580916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee86f15393d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=50), nullable=True),
    sa.Column('rg', sa.String(length=50), nullable=True),
    sa.Column('rua', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rua')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucional', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('professor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado1', sa.String(length=1000), nullable=True),
    sa.Column('enunciado2', sa.String(length=1000), nullable=True),
    sa.Column('enunciado3', sa.String(length=1000), nullable=True),
    sa.Column('enunciado4', sa.String(length=1000), nullable=True),
    sa.Column('resposta', sa.String(length=1000), nullable=True),
    sa.Column('disciplina', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questoes')
    op.drop_table('disciplinas')
    op.drop_table('professores')
    op.drop_table('alunos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
